name: Speex
options:
  bundleIdPrefix: com.andresilvagomez
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.3"
  generateEmptyDirectories: true

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit
    from: "0.12.0"
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.2.0"
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.6.0"
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
  GoogleSignIn-iOS:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "8.0.0"

targets:
  Speex:
    type: application
    platform: macOS
    sources:
      - path: Speex
    preBuildScripts:
      - name: Embed Turbo Model
        script: bash "$SRCROOT/scripts/embed_turbo_model.sh"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.andresilvagomez.speex
        MARKETING_VERSION: "0.0.4"
        CURRENT_PROJECT_VERSION: "4"
        INFOPLIST_FILE: Speex/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Speex/Resources/Speex.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: 7NBJJ9P97F
        CODE_SIGN_IDENTITY: "Apple Development"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: false
        ENABLE_APP_SANDBOX: false
    dependencies:
      - package: WhisperKit
      - package: KeyboardShortcuts
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseAppCheck
      - package: GoogleSignIn-iOS
        product: GoogleSignIn
      - package: Sparkle
    entitlements:
      path: Speex/Resources/Speex.entitlements
      properties:
        com.apple.security.device.audio-input: true
        com.apple.security.automation.apple-events: true

  SpeexTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: SpeexTests
    settings:
      base:
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: Speex
