name: Wisper
options:
  bundleIdPrefix: com.andresilvagomez
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.3"
  generateEmptyDirectories: true

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit
    from: "0.12.0"
  HotKey:
    url: https://github.com/soffes/HotKey
    from: "0.2.1"
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.2.0"

targets:
  Wisper:
    type: application
    platform: macOS
    sources:
      - path: Wisper
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.andresilvagomez.wisper
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Wisper/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Wisper/Resources/Wisper.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_STYLE: Automatic
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: false
        ENABLE_APP_SANDBOX: false
    dependencies:
      - package: WhisperKit
      - package: HotKey
      - package: KeyboardShortcuts
    entitlements:
      path: Wisper/Resources/Wisper.entitlements
      properties:
        com.apple.security.device.audio-input: true
        com.apple.security.automation.apple-events: true
