import Foundation

enum LanguageCatalog {
    static let availableLanguages: [(code: String, name: String)] = [
        ("auto", "Auto (Detect language)"),
        ("af", "Afrikaans"),
        ("am", "Amharic"),
        ("ar", "العربية"),
        ("as", "Assamese"),
        ("az", "Azerbaijani"),
        ("az-Cyrl", "Azerbaijani (Cyrillic)"),
        ("ba", "Bashkir"),
        ("be", "Belarusian"),
        ("bg", "Български"),
        ("bn", "বাংলা"),
        ("bo", "Tibetan"),
        ("br", "Breton"),
        ("bs", "Bosnian"),
        ("ca", "Català"),
        ("cs", "Čeština"),
        ("cy", "Cymraeg"),
        ("da", "Dansk"),
        ("es", "Español"),
        ("et", "Eesti"),
        ("eu", "Euskara"),
        ("fa", "فارسی"),
        ("fi", "Suomi"),
        ("fo", "Faroese"),
        ("gl", "Galego"),
        ("gu", "ગુજરાતી"),
        ("ha", "Hausa"),
        ("haw", "Hawaiian"),
        ("he", "עברית"),
        ("hi", "हिन्दी"),
        ("hr", "Hrvatski"),
        ("ht", "Haitian Creole"),
        ("hu", "Magyar"),
        ("hy", "Հայերեն"),
        ("id", "Bahasa Indonesia"),
        ("is", "Íslenska"),
        ("jv", "Javanese"),
        ("ka", "ქართული"),
        ("kk", "Қазақ"),
        ("km", "ខ្មែរ"),
        ("kn", "ಕನ್ನಡ"),
        ("la", "Latin"),
        ("lb", "Luxembourgish"),
        ("ln", "Lingala"),
        ("lo", "ລາວ"),
        ("lt", "Lietuvių"),
        ("lv", "Latviešu"),
        ("mg", "Malagasy"),
        ("mi", "Māori"),
        ("mk", "Македонски"),
        ("ml", "മലയാളം"),
        ("mn", "Монгол"),
        ("mr", "मराठी"),
        ("ms", "Bahasa Melayu"),
        ("mt", "Malti"),
        ("my", "မြန်မာ"),
        ("ne", "नेपाली"),
        ("nl", "Nederlands"),
        ("nn", "Nynorsk"),
        ("no", "Norsk"),
        ("oc", "Occitan"),
        ("pa", "ਪੰਜਾਬੀ"),
        ("pl", "Polski"),
        ("ps", "پښتو"),
        ("en", "English"),
        ("en-GB", "English (UK)"),
        ("en-US", "English (US)"),
        ("pt", "Português"),
        ("pt-BR", "Português (Brasil)"),
        ("pt-PT", "Português (Portugal)"),
        ("fr", "Français"),
        ("de", "Deutsch"),
        ("it", "Italiano"),
        ("ro", "Română"),
        ("ru", "Русский"),
        ("sa", "Sanskrit"),
        ("sd", "Sindhi"),
        ("si", "සිංහල"),
        ("sk", "Slovenčina"),
        ("sl", "Slovenščina"),
        ("sn", "Shona"),
        ("so", "Soomaali"),
        ("sq", "Shqip"),
        ("sr", "Српски"),
        ("su", "Sundanese"),
        ("sv", "Svenska"),
        ("sw", "Kiswahili"),
        ("ta", "தமிழ்"),
        ("te", "తెలుగు"),
        ("tg", "Тоҷикӣ"),
        ("th", "ไทย"),
        ("tk", "Türkmen"),
        ("tl", "Tagalog"),
        ("tr", "Türkçe"),
        ("tt", "Татар"),
        ("uk", "Українська"),
        ("ur", "اردو"),
        ("uz", "Oʻzbek"),
        ("vi", "Tiếng Việt"),
        ("yi", "ייִדיש"),
        ("yo", "Yorùbá"),
        ("yue", "粵語"),
        ("ja", "日本語"),
        ("ko", "한국어"),
        ("zh-Hans", "中文（简体）"),
        ("zh-Hant", "中文（繁體）"),
        ("zh", "中文"),
    ]

    static let availableInterfaceLanguages: [(code: String, name: String)] = [
        ("system", "System"),
        ("es", "Español"),
        ("en", "English"),
        ("pt", "Português"),
        ("fr", "Français"),
        ("de", "Deutsch"),
    ]

    static func normalizeWhisperLanguageCode(_ code: String) -> String {
        switch code.lowercased() {
        case "pt-br", "pt-pt":
            return "pt"
        case "en-gb", "en-us":
            return "en"
        case "zh-hans", "zh-hant":
            return "zh"
        case "az-cyrl":
            return "az"
        default:
            return code
        }
    }
}
